name: autobuild-when-commit
run-name: "${{ github.actor }}: Autobuild (push)"
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages for static wallpapers builder
        working-directory: ./build
        run: npm install
      - name: Build static wallpapers
        run: node build
      - name: Upload wallpapers as tarball artifact
        uses: actions/upload-artifact@v3
        with:
          name: Static Wallpapers
          path: buildresult/*.png

